### ISSUE TITLE
Missing assembly reference - TransactionServiceInventoryLookupSearchCriteria

### ISSUE THREAD

**Issue by vasireddy** [microsoft/Dynamics365Commerce.ScaleUnit#26]
We are consuming "TransactionServiceInventoryLookupSearchCriteria" class which is in "Microsoft.Dynamics.Commerce.Runtime.TransactionService" assembly. As per documentation provided 
(https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/migrate-commerce-sdk#reference-package-difference-between-legacy-retail-sdk-and-commerce-sdk )
we are consuming "Microsoft.Dynamics.Commerce.Sdk.Runtime". Compilation is failing on this class because of missing assembly reference.

Need some help. Thanks

**Comment by vasireddy** [comment]
@lukedgr any recommendation ?

**Comment by Pikhulya** [comment]
There are no plans to ship the assembly Microsoft.Dynamics.Commerce.Runtime.TransactionService in the Commerce SDK due to potential backward compatibility issues, please see more details in the purple note [here](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-runtime-extensibility#crt-data-service-and-data-service-with-entities). An example on how to make RTS calls from within CRT in a recommended way can be seen in [Call the new method from the CRT](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/extend-commerce-data-exchange#call-the-new-method-from-the-crt)
