### ISSUE TITLE
Store Commerce App unable to play audio from local file

### ISSUE THREAD

**Issue by Caleb-Garvey** [microsoft/Dynamics365Commerce.ScaleUnit#38]
We are trying to do a customization that results in playing an audio file. We have done this in the past with the RetailSDK, but it appears to no longer be working with the CommerceSDK. Hoping to get some feedback on potential options. 

I have added a Sounds folder under the Resources folder in my POS project in the CommerceSDK. When we build the CommerceSDK locally it is replicating this audio resource folder to C:\Program Files\Microsoft Dynamics 365\10.0\Store Commerce\Extensions\BHS.Commerce\POS\Resources\Sounds\alarm.mp3. 
 
At runtime audio.src is set to https://local.storecommerce.dynamics.com/Extensions/MyExtension/Resources/Sounds/alarm.mp3, and it doesn’t give me an error, but the audio doesn’t play. I have confirmed the SCA's ability to play audio with this code by replacing the local call with a URL to an MP3 (https://www.soundjay.com/misc/sounds/bell-ringing-01c.mp3) which is played. 
However, we need to support this functionality in offline mode, so we are hoping to have it available as a local resource. 

Ultimately, I've confirmed that the code playing the audio is working so the issue has to do with the location of the audio file in my resources and/or how the CommerceSDK is making that resource available at the SCA. Any advice on how to link the resource up with my codebase would be greatly appreciated.
<img width="1784" alt="dev tools screenshot audio issue" src="https://user-images.githubusercontent.com/61299201/234659728-43e8ac11-48b8-4b93-aab9-bf7342c6155f.png">

**Comment by madyke** [comment]
Hi @Caleb-Garvey - extension resources like this sound file would be loaded from `extensions.local.storecommerce.dynamics.com`. If you hardcode that instead of `window.location.origin` on line 105 of the screenshot you attached, then it should be looking in the correct hostname at least. (At some point we would like to provide a method that would return the correct location based on application type, but for now hardcoding that endpoint should be sufficient.)

You would then have to update your extension code to load the sound file into whatever folder structure you want for your resource files. Then the hostname + that relative path should load the file correctly.

**Comment by Caleb-Garvey** [comment]
Hi @madyke, I changed my code at line 105 to be

let filePath = "extensions.local.storecommerce.dynamics.com/Extensions/" + extensionPackageName + "/" + relativePathInExtensionPackage; 

At runtime though, https://local.storecommerce.dynamics.com gets added to the front of that file path and the audio doesn't play. So at runtime in the debugger, src looks like "https://local.storecommerce.dynamics.com/extensions.local.storecommerce.dynamics.com/Extensions/..."

Is there a way to prevent https://local.storecommerce.dynamics.com from getting added to the front of the url?

**Comment by Caleb-Garvey** [comment]
@madyke thank you, I'm now seeing the beeper.src path we want. However, the audio still isn't playing. 

I'm thinking it's because I don't see my alarm.mp3 file loaded in the debugger under extensions.local.storecommerce.dynamics.com
<img width="243" alt="Screenshot 2023-05-15 092258" src="https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/assets/61299201/8b17afca-92d7-48de-919e-6f4f4fc58451">
Is there a way to get an mp3 file to load in this extensions directory?

**Comment by madyke** [comment]
Hi @Caleb-Garvey - I confirmed with Luke that there isn't actually a way for us to load it into the framework so that the resource file is displayed in that list, but there is some pathing work done behind the scenes that should still pull the file from the correct extensions directory.

I took a look at the code for that pathing construction, and I think the last step in your case is to remove the `/Extensions` segment from the filepath you're setting up on line 105:

```
let filePath = "https://extensions.local.storecommerce.dynamics.com/" + extensionPackageName + "/" + relativePathInExtensionPackage;
```

With where you said the file is being replicated to, that should get the URL mapped to the correct location in the installed extension folder.

**Comment by Caleb-Garvey** [comment]
That worked, it plays the audio now. Thanks @madyke!
